# permissions for end users to edit keychainsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keychainsecret-editor-role
rules:
- apiGroups:
  - aqueduct.k8s.facebook.com
  resources:
  - keychainsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aqueduct.k8s.facebook.com
  resources:
  - keychainsecrets/status
  verbs:
  - get
