# permissions for end users to view keychainsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keychainsecret-viewer-role
rules:
- apiGroups:
  - aqueduct.k8s.facebook.com
  resources:
  - keychainsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aqueduct.k8s.facebook.com
  resources:
  - keychainsecrets/status
  verbs:
  - get
